#!/usr/bin/env python3
"""Write the ADR-0006 role matrix to a JSON file the web app renders.

    cd apps/backend && uv run python scripts/export_access_matrix.py

The login screen *is* the access matrix (sprint 10, Opsi C), so a matrix drawn from a
hand-maintained TypeScript constant would be a page that can quietly start lying about what
the server permits. The server's `CAPABILITIES` is the single source; this writes it out, and
`tests/test_access.py::test_the_exported_access_matrix_matches_the_server` fails the moment the
committed file drifts from it — the same discipline `export_demo_samples.py` already follows.

Run it after any change to `app/service/access.py`.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.service.access import CAPABILITIES, Capability, Role  # noqa: E402

TARGET = (
    Path(__file__).resolve().parents[3] / "apps" / "web" / "src" / "features" / "auth"
    / "access-matrix.json"
)

BANNER = (
    "GENERATED by apps/backend/scripts/export_access_matrix.py from app/service/access.py. "
    "Do not edit by hand — the server is the source, and a test asserts these match."
)


def payload() -> dict:
    """Roles in declaration order, each with its capabilities sorted for a stable diff."""
    return {
        "_generated": BANNER,
        "capabilities": [str(capability) for capability in Capability],
        "roles": {
            str(role): sorted(str(capability) for capability in CAPABILITIES[role])
            for role in Role
        },
    }


def main() -> int:
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(json.dumps(payload(), indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {TARGET} ({len(Role)} roles, {len(Capability)} capabilities)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
