"""ingestions and evidence edges

Revision ID: 3cf7d9b9fb28
Revises: 
Create Date: 2026-08-31 08:30:43.956738

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cf7d9b9fb28'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bundle_id', sa.String(length=128), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('edge_type', sa.String(length=48), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('derivation_rule', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.CheckConstraint('confidence is null or (confidence >= 0.0 and confidence <= 1.0)', name='ck_evidence_edges_confidence_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_edges_slice', 'evidence_edges', ['bundle_id', 'ruleset_version'], unique=False)
    op.create_index('ix_evidence_edges_source', 'evidence_edges', ['bundle_id', 'ruleset_version', 'source_id'], unique=False)
    op.create_index('ix_evidence_edges_target', 'evidence_edges', ['bundle_id', 'ruleset_version', 'target_id'], unique=False)
    op.create_table('ingestions',
    sa.Column('ingestion_id', sa.String(length=128), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('bundle_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('completeness_notes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('resource_counts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.CheckConstraint("status in ('VALID', 'VALID_WITH_NOTES', 'INVALID')", name='ck_ingestions_status'),
    sa.PrimaryKeyConstraint('ingestion_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_ingestions_input_hash', 'ingestions', ['input_hash'], unique=False)
    op.create_index('ix_ingestions_received_at', 'ingestions', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestions_received_at', table_name='ingestions')
    op.drop_index('ix_ingestions_input_hash', table_name='ingestions')
    op.drop_table('ingestions')
    op.drop_index('ix_evidence_edges_target', table_name='evidence_edges')
    op.drop_index('ix_evidence_edges_source', table_name='evidence_edges')
    op.drop_index('ix_evidence_edges_slice', table_name='evidence_edges')
    op.drop_table('evidence_edges')
    # ### end Alembic commands ###
