"""cases and append-only audit events

Revision ID: c44b0f894fc2
Revises: 3cf7d9b9fb28
Create Date: 2026-08-31 23:03:34.006747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.store.tables import APPEND_ONLY_TRIGGER_SQL, DROP_APPEND_ONLY_TRIGGER_SQL
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c44b0f894fc2'
down_revision: Union[str, Sequence[str], None] = '3cf7d9b9fb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('event_kind', sa.String(length=32), nullable=False),
    sa.Column('actor_role', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('structured_reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('state_before', sa.String(length=32), nullable=True),
    sa.Column('state_after', sa.String(length=32), nullable=True),
    sa.Column('case_version_before', sa.Integer(), nullable=True),
    sa.Column('case_version_after', sa.Integer(), nullable=True),
    sa.Column('supersedes_event_id', sa.String(length=128), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('ruleset_version', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('dataset_version', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_kind <> 'DISPOSITION' or (structured_reason is not null and length(btrim(structured_reason)) > 0)", name='ck_audit_disposition_requires_reason'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_audit_case', 'audit_events', ['case_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_supersedes', 'audit_events', ['supersedes_event_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('ingestion_id', sa.String(length=128), nullable=False),
    sa.Column('bundle_id', sa.String(length=128), nullable=False),
    sa.Column('case_version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('band', sa.String(length=32), nullable=False),
    sa.Column('participant_token', sa.String(length=128), nullable=False),
    sa.Column('provider_token', sa.String(length=128), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='IDR', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completeness_notes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('case_version >= 1', name='ck_cases_version_positive'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index('ix_cases_band', 'cases', ['band'], unique=False)
    op.create_index('ix_cases_created_at', 'cases', ['created_at'], unique=False)
    op.create_index('ix_cases_ingestion', 'cases', ['ingestion_id'], unique=False)
    op.create_index('ix_cases_state', 'cases', ['state'], unique=False)
    # Append-only is a database guarantee, not a convention. Without this an audit trail
    # could be rewritten by anything holding a connection, which would make it not an audit
    # trail at all.
    op.execute(APPEND_ONLY_TRIGGER_SQL)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(DROP_APPEND_ONLY_TRIGGER_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cases_state', table_name='cases')
    op.drop_index('ix_cases_ingestion', table_name='cases')
    op.drop_index('ix_cases_created_at', table_name='cases')
    op.drop_index('ix_cases_band', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_audit_supersedes', table_name='audit_events')
    op.drop_index('ix_audit_case', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
