"""Generate the data card that ships with a corpus.

`docs/canonical/04_data_card.md` § Data card acceptance criteria names eleven required elements
and one mandatory sentence. Both are enforced here and asserted in tests, because a data card
that quietly loses its limitations section is worse than none: it looks like disclosure.
"""
from __future__ import annotations

from dataclasses import dataclass

MANDATORY_SENTENCE = (
    "This dataset is synthetic and does not represent JKN prevalence or real provider behavior."
)
"""Required verbatim by the canonical data card. Not paraphrased, not softened."""

REQUIRED_ELEMENTS: tuple[str, ...] = (
    "Source",
    "License and terms",
    "Generation version",
    "Schema",
    "Population",
    "Injection logic",
    "Split logic",
    "Missingness",
    "Known biases",
    "Prohibited uses",
    "Rounding tolerance",
)


@dataclass(frozen=True)
class CorpusStats:
    bundles: int
    participants: int
    providers: int
    injections: int
    injections_by_mode: dict[str, int]
    multi_label_ratio: float
    train: int
    validation: int
    test: int
    excluded_demo: int
    corpus_hash: str
    seed: int
    leakage_summary: str


def render(stats: CorpusStats, *, generator_version: str, rounding_tolerance: str) -> str:
    """Produce the data card as Markdown."""
    modes = "\n".join(
        f"| {mode} | {count} |" for mode, count in sorted(stats.injections_by_mode.items())
    )
    return f"""# Data Card — TilikKlaim synthetic corpus

> {MANDATORY_SENTENCE}

Generated by `packages/data` at version {generator_version}, seed `{stats.seed}`.
Corpus digest `{stats.corpus_hash}`.

## Source

Generated wholly by project code. **No patient record of any origin was used** — not real, not
public, not from a third-party synthetic dataset. There is no upstream corpus to attribute.
See `docs/canonical/decisions/ADR-0003-native-generator-instead-of-synthea.md` for why Synthea
is not the source.

## License and terms

The generator and everything it produces are part of this repository and carry its licence.
No third-party data licence applies, because no third-party data is involved.

## Generation version

Generator {generator_version}, seed `{stats.seed}`. One seed reproduces the corpus byte for
byte; the digest above is how that is checked.

## Schema

`tilik_domain.canonical.CanonicalBundle` — claim header, claim lines, encounters, conditions,
procedures, medications, diagnostics, documents, accounts, charge items, invoices, provenance.

## Population

| Property | Value |
|---|---|
| Bundles | {stats.bundles} |
| Participants | {stats.participants} |
| Providers | {stats.providers} |

Pseudonymous identifiers only. No names, no NIK, no date of birth, no address. The population
is a **test-design choice** and reflects no real catchment, case mix, or demographic profile.

## Injection logic

{stats.injections} injections, labelled as **injection ground truth** — never as fraud labels.

| Mode | Injections |
|---|---|
{modes}

Multi-label proportion {stats.multi_label_ratio:.3f} — a **measured** value, not a target. Some
bundles deliberately carry more than one injection, because real claims carry several problems at
once and an evaluation assuming one cause per case would measure an easier problem. The
configured figure is the probability of reusing a bundle; because repeat and unbundling each
produce two bundles, the realised proportion lands somewhat above it. Each label records the expected reason codes,
the expected evidence references, the violated invariant, and a difficulty tier.

The clean corpus is verified **before** any injection. Injecting into an already-inconsistent
record would produce a label that misdescribes why a detector fired.

## Split logic

| Partition | Bundles |
|---|---|
| Train | {stats.train} |
| Validation | {stats.validation} |
| Test | {stats.test} |
| Excluded demo fixtures | {stats.excluded_demo} |

Grouped by `(participant, provider-time-block)`, never a random row split — related claims must
not straddle a partition. The test partition is frozen and its digest recorded, so a change to
it is detectable. Validation injections select thresholds only; they are never fitted on. The
five gold demo fixtures sit outside every partition.

## Missingness

Roughly 40% of encounters carry no clinical note, and not every claim carries a medication line.
This is deliberate: a corpus where every record is complete would make the incomplete-bundle
path untestable, and that path is what keeps a missing record from reading as a missing service.

## Known biases

- **No clinical realism.** Codes are invented, care pathways are not modelled, and comorbidity,
  seasonality, referral patterns, and length-of-stay distributions are absent.
- **Amounts are illustrative.** Chosen so line arithmetic is checkable, not to resemble tariffs.
- **Uniform participant and provider draw.** Real claim volume is heavily skewed; this is not.
- **Injected prevalence is a test-design choice**, set to make evaluation tractable. It is far
  above any plausible real rate and must never be quoted as one.
- **Notes come from a handful of templates.** Clean-note variety is bounded, which likely makes
  clone detection easier here than it would be in the field.

## Prohibited uses

- Estimating JKN fraud prevalence, provider behaviour, cost, or utilisation.
- Training any model intended for real claims without revalidation on authorised real data.
- Any claim of clinical validity, or presentation of an amount as a real tariff.
- Any statement about a real person, facility, or payer. None exists in this data.

## Rounding tolerance

Amounts reconcile within {rounding_tolerance}. Documented here and asserted in tests rather than
hidden inside a float comparison.

## Leakage probe

{stats.leakage_summary}

A probe scoring near-perfectly is an **alarm that halts evaluation**, not a pass: it means the
answer is recoverable from identifiers and ordering alone, and every metric would be measuring
bookkeeping instead of detection.
"""


def missing_elements(card: str) -> tuple[str, ...]:
    """Which required elements a rendered card fails to mention."""
    return tuple(element for element in REQUIRED_ELEMENTS if f"## {element}" not in card)
