"""Generate the model card that ships beside a fitted model.

`docs/canonical/05_model_card.md` § Model/version artifacts names eight sections a card must
state. All eight are enforced here and asserted in tests, for the same reason the data card
enforces its own: a card that quietly loses its limitations section is worse than none, because
it looks like disclosure.

Every number in the card comes from the fitted model — the thresholds it actually holds, the
hyperparameters it was fitted under, the feature schema it reads. § 20's constraint is that
every metric quoted in the proposal is a generated artifact, so the metrics section says the
measurement is pending and names the sprint that produces it rather than carrying a figure
somebody typed.
"""
from __future__ import annotations

from dataclasses import dataclass

from tilik_model.calibration import (
    CALIBRATION_PARTITION,
    DRIFT_TOLERANCE,
    HIGH_PRIORITY_QUANTILE,
    NEEDS_CONTEXT_QUANTILE,
)
from tilik_model.feature_schema import FEATURE_SCHEMA
from tilik_model.ranking import (
    DUPLICATE_FINGERPRINT_FLOOR,
    SIMILARITY_ONLY_CEILING,
    RankingModel,
)
from tilik_model.similarity import MINIMUM_NOTE_CHARACTERS, NGRAM_RANGE

MANDATORY_SENTENCE = (
    "This model proposes a queue position for human review. It never states a finding, never "
    "decides a claim, and never triggers a payment action, a sanction, or a code change."
)
"""Required verbatim. The ethical core belongs in the artifact, not only in a conversation."""

METRICS_PENDING_NOTE = (
    "No metric is quoted here. Sprint 06 measures precision@K and recall@K against the frozen "
    "test partition and writes them to a generated artifact; a number typed into this card "
    "before that measurement exists would be a claim with nothing behind it."
)

REQUIRED_ELEMENTS: tuple[str, ...] = (
    "Intended use",
    "Prohibited use",
    "Data",
    "Features",
    "Metrics",
    "Limitations",
    "Fairness",
    "Human oversight",
    "Monitoring",
)


@dataclass(frozen=True)
class ModelCardInputs:
    """Everything the card reports, taken from the fitted model rather than restated."""

    model: RankingModel
    training_bundles: int
    validation_bundles: int
    dropped_contaminated_bundles: int


def missing_elements(card: str) -> tuple[str, ...]:
    """Which required sections a rendered card does not contain."""
    return tuple(element for element in REQUIRED_ELEMENTS if f"## {element}" not in card)


def render(inputs: ModelCardInputs) -> str:
    """Produce the model card as Markdown."""
    model = inputs.model
    return "\n".join(
        (
            _header(inputs),
            _intended_use(),
            _data(inputs),
            _features(),
            _metrics(),
            _limitations(),
            _fairness(),
            _oversight(model),
            _monitoring(model),
        )
    )


def _header(inputs: ModelCardInputs) -> str:
    return f"""# Model Card — TilikKlaim ranking baselines

> {MANDATORY_SENTENCE}

{inputs.model.identity.as_label()}
"""


def _intended_use() -> str:
    return f"""## Intended use

Ordering a review queue of synthetic claim bundles, so that within a fixed review budget the
most informative cases are seen first. The rules layer produces the reasons a reviewer reads;
this layer only proposes where a case sits in the queue, and every reason stays visible beside
it.

The aggregation is fixed by the canonical model card:

    priority = max(deterministic_reason_priority, calibrated_similarity, calibrated_anomaly)

Three caps apply to it, and each exists to stop a specific harm:

- text similarity alone can reach at most **{SIMILARITY_ONLY_CEILING}** — shared forms and
  templates produce very high similarity between notes nobody copied;
- an exact duplicate fingerprint is raised to **{DUPLICATE_FINGERPRINT_FLOOR}** and is still
  reviewed by a person;
- missing evidence on an incomplete bundle lowers the band by one and routes to *request
  evidence*, never toward confirming anything. This cap is applied last, so it overrides the
  other two.

## Prohibited use

- Deciding, rejecting, or paying a claim. Nothing here produces a decision.
- Stating that a person or facility did anything. The corpus contains no real person or
  facility, and no score is a statement about conduct.
- Screening real JKN claims. The model is fitted on synthetic data and would require
  revalidation on authorised real data before it could mean anything.
- Any clinical use. Medical necessity and diagnosis are out of scope.
- Quoting a score as a prevalence, a cost, or a rate of anything.
"""


def _data(inputs: ModelCardInputs) -> str:
    return f"""## Data

Wholly synthetic, generated by `packages/data`; see its `DATA_CARD.md` for the corpus itself.
Dataset digest `{inputs.model.identity.dataset_digest}`.

| Partition | Bundles | Used for |
|---|---|---|
| Train | {inputs.training_bundles} | fitting the peer profile, the vectoriser, and the forest |
| Validation | {inputs.validation_bundles} | band thresholds only — never fitted on |
| Test | — | untouched here; Sprint 06 measures against it |

{inputs.dropped_contaminated_bundles} training bundles were **dropped** before fitting because
their participant also appears in validation or test. The published split groups by
`(participant, facility, time block)`, so one participant can legitimately appear in two
partitions at a different facility or in a different month. That is fine for the corpus and is
not fine for fitting, and re-cutting a split announced as frozen would be a worse remedy than
filtering the training side and reporting the count.
"""


def _features() -> str:
    rows = "\n".join(
        f"| `{spec.name}` | {spec.family} | {spec.description} | `{spec.imputation}` — "
        f"{spec.imputation_note} |"
        for spec in FEATURE_SCHEMA
    )
    return f"""## Features

{len(FEATURE_SCHEMA)} features across the six families named in the canonical model card. No
demographic or protected characteristic appears in any of them: the four risk modes do not need
them, and the canonical card excludes them until an authorised fairness analysis establishes a
purpose.

Every column declares what it means when it cannot be measured. A missing measurement arriving
as a confident `0.0` would make "no peer group to compare against" and "exactly average for its
peer group" indistinguishable, so every imputed column is named on the row it appears in.

| Feature | Family | What it measures | When it cannot be measured |
|---|---|---|---|
{rows}

**No feature reads an identifier.** Identifiers are used only for equality — does this reference
resolve, is this the same facility. The test suite proves it by re-identifying an entire corpus
and asserting the feature table does not move, which covers the injector suffix, the record
ordinal, and anything else an identifier could carry.
"""


def _metrics() -> str:
    return f"""## Metrics

{METRICS_PENDING_NOTE}

The comparison that matters is **incremental**: this layer is justified only if it improves
precision@K or recall@K over the rules-only baseline at the same review budget. If it does not,
`sprint/backlog/05-ranking-models/sprint.md` says to remove it, and
`docs/canonical/01_product_decision.md` records that removing it is not a product kill.
"""


def _limitations() -> str:
    return """## Limitations

- **A band raised only by a model score has no reason to show a reviewer.** The aggregation is
  a plain maximum, so an anomaly score can raise a case the rules layer said nothing about.
  Every such result is flagged `explained_by_reasons: false` rather than suppressed — refusing
  to raise them would be a policy this layer is not entitled to invent on its own. Sprint 06
  decides what the queue does with them.
- **Templated documentation reads as similarity.** The corpus draws notes from a handful of
  templates, which likely makes clone detection easier here than in the field, and real shared
  forms would produce false positives the similarity ceiling exists to contain.
- **The peer group is eight synthetic facilities with a uniform draw.** Real claim volume is
  heavily skewed. Peer deviation measured here says little about how it would behave on a real
  distribution.
- **The anomaly model is unsupervised and label-free.** It notices that a claim is unlike its
  population. It cannot say why, and "unlike" is not "wrong".
- **Short or absent notes make similarity inert**, not zero-risk. Roughly 40% of encounters
  carry no note at all, so for those claims this component contributes nothing and the absence
  is not evidence of anything.
- **Fitted on synthetic data.** Nothing here transfers to real claims without revalidation.
"""


def _fairness() -> str:
    return """## Fairness

No demographic or protected characteristic is used, and none exists in the canonical schema —
there is no name, no NIK, no date of birth, no address, and no sex. Participant and facility
identifiers are pseudonymous tokens and are used only as grouping keys, never as values.

Peer-context features compare a claim to **its own facility's** usual pattern, not facilities to
each other. Comparing facilities against a single global distribution would systematically
disadvantage small or atypical ones for being small, which is a fairness failure dressed as a
statistical one.

Because no protected attribute exists in the data, no subgroup performance analysis is possible
here. That is a limitation of this evaluation, not evidence of fairness, and it must not be
reported as the latter.
"""


def _oversight(model: RankingModel) -> str:
    return f"""## Human oversight

Every case is dispositioned by a person, and this layer proposes only a queue position. It emits
no disposition other than *request evidence*, and never confirming, rejecting, or escalating —
a score is not an argument a reviewer can weigh, and it must not look like one.

A statistical score can never reach `DETERMINISTIC_CONFLICT`. That band means a versioned
invariant was violated outright, which the rules layer observes and a forest cannot.

Every component score and version is stored beside the aggregate, so a band can be explained
rather than trusted, and the caps that were applied are recorded by name.

| Threshold | Value | Fitted on |
|---|---|---|
{_threshold_rows(model)}

Thresholds are fitted on the **{CALIBRATION_PARTITION}** partition only, and `BandCalibration.fit`
refuses any other partition by name rather than trusting the caller. A cut point placed against
training rows sits in the wrong part of the distribution; one placed against test rows is a
threshold tuned on the exam.

Hyperparameters: {model.anomaly.hyperparameters}. Similarity uses character n-grams
{NGRAM_RANGE} and ignores any note shorter than {MINIMUM_NOTE_CHARACTERS} characters, because
two notes reading "ok" are identical and mean nothing.
"""


def _threshold_rows(model: RankingModel) -> str:
    """The four cut points the model actually holds, as table rows."""
    fitted = f"{CALIBRATION_PARTITION} (quantile {NEEDS_CONTEXT_QUANTILE})"
    high = f"{CALIBRATION_PARTITION} (quantile {HIGH_PRIORITY_QUANTILE})"
    similarity = model.similarity_calibration
    anomaly = model.anomaly_calibration
    return "\n".join(
        (
            f"| Similarity → needs context | {similarity.needs_context_at:.4f} | {fitted} |",
            (
                f"| Similarity → high priority | {similarity.high_priority_at:.4f} "
                f"| capped at {SIMILARITY_ONLY_CEILING} |"
            ),
            f"| Anomaly → needs context | {anomaly.needs_context_at:.4f} | {fitted} |",
            f"| Anomaly → high priority | {anomaly.high_priority_at:.4f} | {high} |",
        )
    )


def _monitoring(model: RankingModel) -> str:
    return f"""## Monitoring

`BandCalibration.drift_against` compares a new population's score distribution to the one the
thresholds were set against, at quantiles reported individually rather than averaged away. A
shift beyond {DRIFT_TOLERANCE:.2f} at any quantile is reported for a person to act on.

Drift is **reported, not acted on**. Silently re-fitting thresholds when the population moves
would make an old case and a new case incomparable without anyone noticing, and an audited
decision has to stay interpretable under the version that produced it.

What to watch, and what each would mean:

- a rising share of cases with `explained_by_reasons: false` — the model is raising cases the
  rules cannot explain, and the queue is drifting away from reviewable evidence;
- a rising share of imputed peer features — new facilities are arriving faster than the profile
  is refitted, so peer deviation is quietly becoming an absence rather than a measurement;
- a rising share of claims with no usable note — the similarity component is going inert, and
  its silence must not be read as an absence of risk.
"""
